routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login', ['title' => 'Login']);
});

// Route::get('/register/success', function () {
//     $view = [
//         'title' => 'Thanks for Registration!',
//     ];
//     return view('welcome', $view);
// })->name('register.success');

Auth::routes();
Route::post('/login/submit', 'Auth\LoginController@Login')->name('login.submit');

// School
Route::prefix('school')->name('school.')->group(function () {
    Route::get('register', 'SchoolController@create')->name('register');
    Route::post('/', 'SchoolController@store')->name('store');
});

Route::prefix('get')->name('get.')->group( function() {
    Route::post('city', 'GetController@city')->name('city');
    Route::post('chart', 'GetController@adminChartSchool')->name('chart');
    Route::post('chartReqJava', 'GetController@chartReqJava')->name('chartReqJava');
    Route::post('chartReqOutJava', 'GetController@chartReqOutJava')->name('chartReqOutJava');
    Route::post('schoolStatus', 'GetController@schoolStatus')->name('schoolStatus');
    Route::post('studentStatus', 'GetController@studentStatus')->name('studentStatus');
    Route::post('regency', 'GetController@regency')->name('regency');
    Route::post('school', 'GetController@school')->name('school');
    Route::post('generation', 'GetController@generation')->name('generation');
    Route::post('unitScore', 'GetController@unitScore')->name('unitScore');
    Route::post('studentAchievement', 'GetController@studentAchievement')->name('studentAchievement');
    Route::post('schoolAchievement', 'GetController@schoolAchievement')->name('schoolAchievement');
    Route::post('student', 'GetController@student')->name('student');
    Route::post('schoolAcademy', 'GetController@schoolAcademy')->name('schoolAcademy');
    Route::post('schoolClassIntensif', 'GetController@schoolClassIntensif')->name('schoolClassIntensif');
    Route::post('talentPool', 'GetController@talentPool')->name('talentPool');
    Route::post('academy', 'GetController@academy')->name('academy');
});


// default guard
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('user', 'UserController')->except(['destroy']);
    Route::prefix('user')->name('user.')->group(function(){
        Route::post('list', 'UserController@list')->name('list');
        Route::post('reset', 'UserController@reset')->name('reset');
        Route::delete('destroy', 'UserController@destroy')->name('destroy');
    });
    Route::resource('psychotest-result', 'PsychologicalTestResultController')->except(['list', 'show']);
    Route::prefix('psychotest-result')->name('psychotest-result.')->group(function(){
        Route::post('mbti_list', 'PsychologicalTestResultController@mbti_list')->name('mbti_list');
        Route::get('{psychologicalTest}/attempt/{psychologicalTestAttempt}/result', 'PsychologicalTestResultController@mbti_show')->name('mbti_show');

        Route::post('disc_list', 'PsychologicalTestResultController@disc_list')->name('disc_list');
        Route::get('{user}/result', 'PsychologicalTestResultController@disc_show')->name('disc_show');
    });
});

// guard Student
Route::middleware(['auth:student'])->group(function () {
    Route::namespace('Student')->prefix('student')->name('student.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::post('/home/store', 'HomeController@store')->name('home.store');
        
        // StudentLesson
        Route::prefix('studentLesson')->name('studentLesson.')->group(function(){
            Route::post('list', 'StudentLessonController@list')->name('list');
            Route::post('reset', 'StudentLessonController@reset')->name('reset');
            Route::delete('destroy', 'StudentLessonController@destroy')->name('destroy');
            Route::post('preCreate', 'StudentLessonController@preCreate')->name('preCreate');
        });
        Route::resource('studentLesson', 'StudentLessonController')->except(['destroy']);

        // profile
        Route::prefix('profile')->name('profile.')->group(function(){
            Route::get('preview/{student}','ProfileController@preview')->name('preview');
            Route::get('download/{student}','ProfileController@download')->name('download');
            Route::post('list', 'ProfileController@list')->name('list');
            Route::post('reset', 'ProfileController@reset')->name('reset');
            Route::delete('destroy', 'ProfileController@destroy')->name('destroy');
        });
        Route::resource('profile', 'ProfileController')->except(['destroy']);
        
        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Teacher
Route::middleware(['auth:teacher'])->group(function () {
    Route::namespace('Teacher')->prefix('facilitator')->name('teacher.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');

        // school
        Route::prefix('school')->name('school.')->group(function(){
            Route::post('list', 'SchoolController@list')->name('list');
            Route::post('reset', 'SchoolController@reset')->name('reset');
            Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
        });
        Route::resource('school', 'schoolController')->except(['destroy']);

        // lesson
        Route::prefix('lesson')->name('lesson.')->group(function(){
            Route::post('list', 'LessonController@list')->name('list');
            Route::post('reset', 'LessonController@reset')->name('reset');
            Route::delete('destroy', 'LessonController@destroy')->name('destroy');
        });
        Route::resource('lesson', 'LessonController')->except(['destroy']);

        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('upload', 'StudentController@upload')->name('upload');
            Route::post('import', 'StudentController@import')->name('import');
            Route::post('export', 'StudentController@export')->name('export');
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });
        Route::resource('student', 'StudentController')->except(['destroy']);

        // new student
        Route::prefix('newStudent')->name('newStudent.')->group(function(){
            Route::get('/import', 'NewStudentController@import')->name('import');
            Route::post('list', 'NewStudentController@list')->name('list');
            Route::post('reset', 'NewStudentController@reset')->name('reset');
            Route::delete('destroy', 'NewStudentController@destroy')->name('destroy');
            Route::delete('approve', 'NewStudentController@approve')->name('approve');
            Route::delete('reject', 'NewStudentController@reject')->name('reject');
        });
        Route::resource('newStudent', 'NewStudentController')->except(['destroy']);

        // Update
        Route::prefix('update')->name('update.')->group(function () {
            Route::post('list', 'UpdateController@list')->name('list');
            Route::get('/', 'UpdateController@index')->name('index');
            Route::prefix('status')->name('status.')->group(function () {
                Route::get('/', 'UpdateController@status')->name('index');
            });
        });

        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Partner
Route::middleware(['auth:partner'])->group(function () {
    Route::namespace('Partner')->prefix('partner')->name('partner.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        
        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Datakrama\Eloquid\Traits\Uuids;

class Student extends Model
{
	use Uuids;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'school_origin', 'phone_number', 'study_status', 'registered_status', 'generation_id', 'place_of_birth', 'date_of_birth', 'gender', 'identition_number', 'city_id', 'address', 'weight', 'height'
    ];
    
    public function generation() {
    	return $this->belongsTo('App\Generation');
    }

    public function school() {
    	return $this->hasOneThrough('App\School', 'App\Generation', 'id', 'id', 'generation_id', 'school_id');
    }

    public function studentStatuses() {
        return $this->hasMany('App\StudentStatus');
    }

    public function statuses() {
        return $this->belongsToMany('App\Status', 'student_statuses')->using('App\StudentStatus')->withTimestamps()->withPivot('created_at');
    }

    public function status() {
    	return $this->statuses()->newest();
    }

    public function statusLatest() {
        return $this->hasOneThrough('App\Status', 'App\StudentStatus', 'student_id', 'id', 'id', 'status_id')->latest();
    }

    public function level() {
    	return $this->status()->level();
    }

    public function user() {
    	return $this->hasOneThrough('App\User', 'App\StudentAccount', 'student_id', 'id', 'id', 'user_id');
    }

    public function city() {
        return $this->belongsTo('App\City');
    }

    public function documents() {
    	return $this->hasMany('App\StudentDocument');
    }

    public function lessonAchievements() {
        return $this->hasMany('App\StudentLessonAchievement');
    }

    // public function achievements() {
    //     return $this->hasManyThrough('App\LessonAchievement', 'App\StudentLessonAchievement', 'student_id', 'id', 'id', 'lesson_achievement_id');
    // }

    public function lesson() {
        return $this->hasMany('App\StudentLesson');
    }
    
    public function alocatedStudent() {
        return $this->hasMany('App\AlocatedStudent');
    }

    // end of relation function

    // attribute function
    public function getProfilePercentageAttribute() {
        $column = collect($this->getAttributes())->except(['id', 'created_at', 'updated_at', 'pivot']);
        return substr(($column->filter(function ($item) { return $item; })->count() / $column->count())*100, 0 , 4 );
    }

}

app/Http/Controllers/Student/AccountController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use Spatie\Image\Manipulations;
use Illuminate\Http\Request;
use Spatie\Image\Image;
use App\User;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, User $user)
    {
        $view = [
            'title' => __('Account Detail'),
            'breadcrumbs' => [
                route('student.account.index') => __('Account'),
                null => __('Detail')
            ],
            'data' => $user
        ];
        if ($request->is('student/account/me/*')) {
            $addonView = [
                'subtitle' => __('Hi') . ', ' . $user->name . '!',
                'description' => __('Change information about yourself on this page.'),
            ];
            $view = array_merge($view, $addonView);
        }
        return view('student.account.show', $view);
    }

    /**
     * Display the current user's resource.
     * 
     * @return @show()
     */
    public function me(Request $request)
    {
        return $this->show($request, auth()->guard('admin')->user());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        if ($request->filled('password')) {
            $request->merge(['password' => Hash::make($request->password)]);
        } else {
            $request->merge(['password' => $user->password]);
        }
        if ($request->hasFile('photo')) {
            $request->merge(['avatar' => $this->uploadPhoto($request)]);
        }
        $user->fill($request->all());
        $user->save();
        return redirect(url()->previous())->with('alert-success', __($this->updatedMessage));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Upload photo
     * 
     * @param  \App\Teacher  $user
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $oldFile
     * @return string
     */
    public function uploadPhoto(Request $request)
    {
        Image::load($request->photo)
            ->fit(Manipulations::FIT_CROP, 150, 150)
            ->optimize()
            ->save();
        $filename = 'photo_'.date('d_m_Y_H_i_s_').md5(uniqid(rand(), true)).'.'.$request->photo->extension();
        $path = $request->photo->storeAs('public/student/photo/', $filename);
        return $filename;
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        //
    }
}

resources/views/student/profile/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-lg-8">
		<div class="card profile-widget">
			<div class="profile-widget-header">                     
				<img alt="image" src="{{ asset('img/avatar/avatar.png') }}" class="rounded-circle profile-widget-picture">
				<div class="profile-widget-items">
					<div class="profile-widget-item">
						<div class="profile-widget-item-value">Nama</div>
						<div class="profile-widget-item-label">{{ $data->name }}</div>
					</div>
					<div class="profile-widget-item">
						<div class="profile-widget-item-value">Akademi</div>
						<div class="profile-widget-item-label">{{ $data->school->name }}</div>
					</div>
					<div class="profile-widget-item">
						<div class="profile-widget-item-value">Status</div>
						<div class="profile-widget-item-label">{{ $data->study_status }}</div>
					</div>
				</div>
			</div>
			<div class="profile-widget-description">
				<ul class="nav nav-tabs" id="myTab" role="tablist">
					<li class="nav-item">
					<a class="nav-link active show" id="akun-tab" data-toggle="tab" href="#akun" role="tab" aria-controls="akun" aria-selected="true">{{ __('Akun') }}</a>
					</li>
					<li class="nav-item">
					<a class="nav-link" id="profil-tab" data-toggle="tab" href="#profil" role="tab" aria-controls="profil" aria-selected="true">{{ __('Profil') }}</a>
					</li>
					<li class="nav-item">
					<a class="nav-link" id="dokumen-tab" data-toggle="tab" href="#dokumen" role="tab" aria-controls="dokumen" aria-selected="false">{{ __('Dokumen') }}</a>
					</li>
					<li class="nav-item">
					<a class="nav-link" id="psikotes-tab" data-toggle="tab" href="#psikotes" role="tab" aria-controls="psikotes" aria-selected="false">{{ __('Psikotes') }}</a>
					</li>
					<li class="nav-item">
					<a class="nav-link" id="raport-tab" data-toggle="tab" href="#raport" role="tab" aria-controls="raport" aria-selected="false">{{ __('Raport') }}</a>
					</li>
				</ul>
				<div class="tab-content" id="myTabContent">
					<div class="tab-pane fade active show" id="akun" role="tabpanel" aria-labelledby="akun-tab">
					{{ Form::open(['route' => ['student.account.update', Auth::user()->id], 'method' => 'put', 'files' => true]) }}
						<div class="row">
                            {{ Form::bsText('col-sm-6', __('Username'), 'username', Auth::user()->username, __('Username'), ['' => '']) }}

                            {{ Form::bsText('col-sm-6', __('Name'), 'name', Auth::user()->name, __('Name'), ['' => '']) }}
                            
                            {{ Form::bsText('col-sm-6', __('Email'), 'email', Auth::user()->email, __('Email'), ['' => '']) }}
                            
                            {{ Form::bsFile('col-sm-6', __('Photo'), 'photo', null, [], [__('Photo with JPG/PNG format up to 5MB.')]) }}

                            {{ Form::bsPassword('col-sm-6', __('Password'), 'password', __('Password'), ['id' => 'password']) }}

							{{ Form::bsPassword('col-sm-6', 'Password Confirmation:', 'password_confirmation', 'Password Confirmation', ['id' => 'password_confirmation'], ['Show Password'], 'true') }}

						</div>
                        {{ Form::submit(__('Submit'), ['class' => 'btn btn-primary btn-block']) }}
					{{ Form::close() }}
					</div>
					<div class="tab-pane fade" id="profil" role="tabpanel" aria-labelledby="profil-tab">
					{{ Form::open(['route' => ['student.profile.update', $data->id], 'method' => 'put', 'files' => true]) }}
						<div class="row">
							{{ Form::bsText('col-lg-6', __('Nama'), 'name', $data->name, $data->name, ['' => '']) }}
							
							{{ Form::bsText('col-lg-6', __('Akademi'), 'academy', $data->school->name, $data->school->name, ['disabled' => '']) }}
							
							{{ Form::bsText('col-lg-6', __('Tempat Lahir'), 'place_of_birth', $data->place_of_birth, $data->place_of_birth, ['' => '']) }}	
							
							{{ Form::bsText('col-lg-6', __('Tanggal Lahir'), 'date_of_birth', $data->date_of_birth, $data->date_of_birth, ['' => '']) }}	
							
							{{ Form::bsText('col-lg-6', __('Jenis Kelamin'), 'gender', $data->gender, $data->gender, ['' => '']) }}	
							
							{{ Form::bsText('col-lg-6', __('Nomor Telpon/Username'), 'phone_number', '(+62) '.$data->phone_number, __('Nomor Telpon'), ['' => '']) }}
							
							{{ Form::bsTextAppend('col-lg-6', __('Berat Badan'), 'weight', $data->weight, $data->weight, 'Kg', ['' => '']) }}	
							
                            {{ Form::bsTextAppend('col-lg-6', __('Tinggi Badan'), 'height', $data->height, $data->height, 'Cm', ['' => '']) }}	     
						</div>
                        {{ Form::submit(__('Submit'), ['class' => 'btn btn-primary btn-block']) }}
                    {{ Form::close() }}
					</div>
					<div class="tab-pane fade" id="dokumen" role="tabpanel" aria-labelledby="dokumen-tab">
						<div class="row">
                            @foreach($documents as $data)
                                {{ Form::bsBrowseFile('col-sm-6', ucwords(str_replace('_', ' ', $data->name)), $data->name, $data->name) }}
                            @endforeach
						</div>
                        {{ Form::submit(__('Submit'), ['class' => 'btn btn-primary btn-block']) }}
					</div>
					<div class="tab-pane fade" id="psikotes" role="tabpanel" aria-labelledby="psikotes-tab">
						<div class="row">
							<h2 class="section-title">Hasil DISC</h2>
							<canvas id="graph-3" width="100%" height="50px"></canvas>

							<h2 class="section-title">Hasil MBTI</h2>
							<div class="table-responsive">
								<table class="table table-striped">
									<thead>
										<tr>
											<th scope="col">#</th>
											<th scope="col" colspan="4" class="text-center">DIMENSION</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>1</td>
											<td>INTROVERT (I)</td>
											<td>33%</td>
											<td>67%</td>
											<td>(E) EKSTROVERT</td>
										</tr>
										<tr>
											<td>2</td>
											<td>SENSING (S)</td>
											<td>27%</td>
											<td>73%</td>
											<td>(N) INTUITION</td>
										</tr>
										<tr>
											<td>3</td>
											<td>THINKING (T)</td>
											<td>60%</td>
											<td>40%</td>
											<td>(F) FEELING</td>
										</tr>
										<tr>
											<td>4</td>
											<td>JUDGING (J)</td>
											<td>40%</td>
											<td>60%</td>
											<td>(P) PERCEIVING</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>				
					</div>
					<div class="tab-pane fade" id="raport" role="tabpanel" aria-labelledby="raport-tab">
						<h4 class="text-center mt-3">{{ __('Raport Siswa') }}</h4>
						<table class="table table-sm">
							<thead>
							<tr>
								<th scope="col">#</th>
								<th scope="col">{{ __('Skill') }}</th>
								<th scope="col">{{ __('KKM') }}</th>
								<th scope="col">{{ __('Nilai') }}</th>
								<th scope="col">{{ __('Nilai Rata-rata') }}</th>
							</tr>
							</thead>
							<tbody>
								@php $no = 1; @endphp
								@foreach($raport as $key)
									<tr>
										<th scope="row">{{ $no++ }}</th>
										<td>{{ $key['lesson'] }}</td>
										<td>{{ $key['kkm'] }}</td>
										<td>{{ $key['flight_hours'] }}</td>
										<td>{{ $key['average'] }} <small></small></td>
									</tr>
								@endforeach
							</tbody>
						</table>
						<div class="text-center">
							<a href="{{ route('student.profile.preview', $data->id) }}" class="btn btn-warning"><i class="far fa-file-pdf"></i> Preview</a>
							<a href="{{ route('student.profile.download', $data->id) }}" class="btn btn-primary"><i class="fas fa-file-download"></i> Download</a>
						</div>
                    </div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-4 d-none">
		<div class="card">
			<div class="card-header"><h4>{{ __('Pencapaian Rata-rata') }}</h4></div>
			<div class="card-body">
				<div class="mb-4">
					<div class="text-small float-right font-weight-bold text-muted">101.67 Stack <small>/ </small> 90:00 Menit</div>
					<div class="font-weight-bold mb-1">Band Uang</div>
					<div class="progress" data-height="5" style="height: 5px;">
						<div class="progress-bar" role="progressbar" data-width="56%" aria-valuenow="56" aria-valuemin="0" aria-valuemax="100" style="width: 56%;"></div>
					</div>
				</div>
				<div class="mb-4">
					<div class="text-small float-right font-weight-bold text-muted">4 Kali <small>/ </small>02:49 Menit</div>
					<div class="font-weight-bold mb-1">Isi Kaset</div>
					<div class="progress" data-height="5" style="height: 5px;">
						<div class="progress-bar" role="progressbar" data-width="64%" aria-valuenow="64" aria-valuemin="0" aria-valuemax="100" style="width: 64%;"></div>
					</div>
				</div>
				<div class="mb-4">
					<div class="text-small float-right font-weight-bold text-muted">4 Kali <small>/ </small> 02:42 Menit</div>
					<div class="font-weight-bold mb-1">Bongkar Kaset</div>
					<div class="progress" data-height="5" style="height: 5px;">
						<div class="progress-bar" role="progressbar" data-width="76%" aria-valuenow="76" aria-valuemin="0" aria-valuemax="100" style="width: 76%;"></div>
					</div>
				</div>
				<div class="mb-4">
					<div class="text-small float-right font-weight-bold text-muted">4 Kali <small>/ </small> 01:52 Menit</div>
					<div class="font-weight-bold mb-1">Pengepakan Plastik</div>
					<div class="progress" data-height="5" style="height: 5px;">
						<div class="progress-bar" role="progressbar" data-width="76%" aria-valuenow="76" aria-valuemin="0" aria-valuemax="100" style="width: 76%;"></div>
					</div>
				</div>
				<div class="mb-4">
					<div class="text-small float-right font-weight-bold text-muted">4 Kali <small>/ </small> 02:15 Menit</div>
					<div class="font-weight-bold mb-1">Pengepakan Kanvas</div>
					<div class="progress" data-height="5" style="height: 5px;">
						<div class="progress-bar" role="progressbar" data-width="85%" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%;"></div>
					</div>
				</div>
				<div class="mb-4">
					<div class="text-small float-right font-weight-bold text-muted">4 Kali <small>/ </small> 00:52 Menit</div>
					<div class="font-weight-bold mb-1">Mengisi Kembali</div>
					<div class="progress" data-height="5" style="height: 5px;">
						<div class="progress-bar" role="progressbar" data-width="32%" aria-valuenow="32" aria-valuemin="0" aria-valuemax="100" style="width: 32%;"></div>
					</div>
				</div>
			</div>
		</div>
    </div>
</div>
@endsection
@section('script')
<script>
	$(document).ready(function(){
	    $('.icon').hover(function () {
	        $('#password').attr('type', 'text');
	        $('#password_confirmation').attr('type', 'text');
	        $('.icon').attr('class', 'fa fa-eye icon');
	    }, function () {
	        $('#password').attr('type', 'password'); 
	        $('#password_confirmation').attr('type', 'password'); 
	        $('.icon').attr('class', 'fa fa-eye-slash icon');
	    });
	});
</script>
<script>	
	var ctx = $("#graph-3");
	var lineChart = new Chart(ctx, {
		type: 'line',
		data: {
			labels: ["D", "I", "S", "C"],
		
			datasets: [
				{
					label: "Graph 3 - Mirror Perceived Self",
					data: ['-1', '-1', '2', '1'],
					pointBackgroundColor: [ "#FF6766", "#FFFF66", "#99CDFF", "#67FF9A" ],
					pointBorderColor: [ "#FF6766", "#FFFF66", "#99CDFF", "#67FF9A" ],
					pointBorderWidth: 5,
					fill: false,
				}   
			]
		},
		options: {
			ticks: {
				stepSize: 0.5
			}

		}
	});
</script>
@endsection