routes/web.php
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Teacher
Route::middleware(['auth:teacher'])->group(function () {
    Route::namespace('Teacher')->prefix('facilitator')->name('teacher.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');

        // school
        Route::prefix('school')->name('school.')->group(function(){
            Route::post('list', 'SchoolController@list')->name('list');
            Route::post('reset', 'SchoolController@reset')->name('reset');
            Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
        });
        Route::resource('school', 'schoolController')->except(['destroy']);

        // lesson
        Route::prefix('lesson')->name('lesson.')->group(function(){
            Route::post('list', 'LessonController@list')->name('list');
            Route::post('reset', 'LessonController@reset')->name('reset');
            Route::delete('destroy', 'LessonController@destroy')->name('destroy');
        });
        Route::resource('lesson', 'LessonController')->except(['destroy']);

        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('upload', 'StudentController@upload')->name('upload');
            Route::post('import', 'StudentController@import')->name('import');
            Route::post('export', 'StudentController@export')->name('export');
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });
        Route::resource('student', 'StudentController')->except(['destroy']);

        // new student
        Route::prefix('newStudent')->name('newStudent.')->group(function(){
            Route::get('/import', 'NewStudentController@import')->name('import');
            Route::post('list', 'NewStudentController@list')->name('list');
            Route::post('reset', 'NewStudentController@reset')->name('reset');
            Route::delete('destroy', 'NewStudentController@destroy')->name('destroy');
            Route::delete('approve', 'NewStudentController@approve')->name('approve');
            Route::delete('reject', 'NewStudentController@reject')->name('reject');
        });
        Route::resource('newStudent', 'NewStudentController')->except(['destroy']);

        // Update
        Route::prefix('update')->name('update.')->group(function () {
            Route::post('list', 'UpdateController@list')->name('list');
            Route::get('/', 'UpdateController@index')->name('index');
            Route::prefix('status')->name('status.')->group(function () {
                Route::get('/', 'UpdateController@status')->name('index');
            });
        });

        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Partner
Route::middleware(['auth:partner'])->group(function () {
    Route::namespace('Partner')->prefix('partner')->name('partner.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        
        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });
        Route::resource('student', 'StudentController')->except(['destroy']);

        // SDM request
        Route::prefix('request')->name('request.')->group(function(){
            Route::post('list', 'RequestController@list')->name('list');
            Route::delete('destroy', 'RequestController@destroy')->name('destroy');
        });
        Route::resource('request', 'RequestController')->except(['destroy']);
        
        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Admin
Route::middleware(['auth:admin'])->group(function () {
    Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::post('/', 'HomeController@index')->name('filterChart');

        // teacher
        Route::resource('teacher', 'TeacherController')->except(['destroy']);
        Route::prefix('teacher')->name('teacher.')->group(function(){
            Route::post('list', 'TeacherController@list')->name('list');
            Route::post('reset', 'TeacherController@reset')->name('reset');
            Route::delete('destroy', 'TeacherController@destroy')->name('destroy');
        });

        // school
        Route::prefix('school')->name('school.')->group(function(){
            Route::post('list', 'SchoolController@list')->name('list');
            Route::post('reset', 'SchoolController@reset')->name('reset');
            Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
        });
        Route::resource('school', 'SchoolController')->except(['destroy']);

        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('import', 'StudentController@import')->name('import');
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('listLogSkill/{student}', 'StudentController@listLogSkill')->name('listLogSkill');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });
        Route::resource('student', 'StudentController')->except(['destroy']);

        // partner
        Route::prefix('partner')->name('partner.')->group(function(){
            Route::post('list', 'PartnerController@list')->name('list');
            Route::post('reset', 'PartnerController@reset')->name('reset');
            Route::delete('destroy', 'PartnerController@destroy')->name('destroy');
        });
        Route::resource('partner', 'PartnerController')->except(['destroy']);

        // psychotest
        Route::prefix('psychotest-result')->name('psychotest-result.')->group(function(){
            Route::post('mbti_list', 'PsychologicalTestResultController@mbti_list')->name('mbti_list');
            Route::get('{psychologicalTest}/attempt/{psychologicalTestAttempt}/result', 'PsychologicalTestResultController@mbti_show')->name('mbti_show');

            Route::post('disc_list', 'PsychologicalTestResultController@disc_list')->name('disc_list');
            Route::get('{user}/result', 'PsychologicalTestResultController@disc_show')->name('disc_show');
        });
        Route::resource('psychotest-result', 'PsychologicalTestResultController')->except(['list', 'show']);

        // training
        Route::prefix('training')->name('training.')->group(function(){
            Route::post('list', 'TrainingController@list')->name('list');
            Route::post('reset', 'TrainingController@reset')->name('reset');
            Route::delete('destroy', 'TrainingController@destroy')->name('destroy');
        });
        Route::resource('training', 'TrainingController')->except(['destroy']);

        // Update
        Route::prefix('update')->name('update.')->group(function () {
            Route::post('list', 'UpdateController@list')->name('list');
            Route::get('/', 'UpdateController@index')->name('index');
            Route::prefix('status')->name('status.')->group(function () {
                Route::get('/', 'UpdateController@status')->name('index');
                Route::post('status/store', 'UpdateController@statusStore')->name('store');
            });
        });

        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });

app/Training.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Datakrama\Eloquid\Traits\Uuids;

class Training extends Model
{
    use Uuids;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug'
    ];

    public function batches() {
    	return $this->hasMany('App\TrainingBatch');
    }

    public function teacherTranings() {
    	return $this->belongsToMany('App\TeacherTraining', 'training_batches')->using('App\TrainingBatch');
    }

    public function teachers() {
    	return $this->teacherTraining()->teachers();
    }
}

app/Http/Controllers/Admin/TrainingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\TrainingBatch;
use App\Training;
use DataTables;

class TrainingController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dd(Training::withCount('batches')->get());
        $view = [
            'title' => __('Training'),
        ];
        return view('admin.training.index', $view);
    }

    /**
     * Show a listing of the resource for datatable.
     * 
     * @param  \Illuminate\Http\Request  $request
     */
    public function list(Request $request)
    {
        if ($request->ajax()) {
            return DataTables::of(Training::withCount('batches')->get())
                ->addColumn('DT_RowIndex', function ($data) {
                    return '<div class="checkbox icheck"><label><input type="checkbox" name="selectedData[]" value="'.$data->id.'"></label></div>';
                })
                ->editColumn('created_at', function ($data) {
                    return (date('d-m-Y H:i:s', strtotime($data->created_at)));
                })
                ->addColumn('batch', function($data) {
                    return $data->batches_count;
                })
                ->addColumn('action', function ($data) {
                    return '<a class="btn btn-icon btn-sm btn-info" href="'.route('admin.training.show', $data->id).'" title="'.__("See detail").'"><i class="fa fa-eye"></i></a> <a class="btn btn-icon btn-sm btn-warning" href="'.route('admin.training.edit', $data->id).'" title="'.__("Edit").'"><i class="fa fa-edit"></i></a>';
                })
                ->rawColumns(['status', 'DT_RowIndex', 'action'])
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use App\Training;
use Illuminate\Http\Request;

class TrainingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Training  $training
     * @return \Illuminate\Http\Response
     */
    public function show(Training $training)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Training  $training
     * @return \Illuminate\Http\Response
     */
    public function edit(Training $training)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Training  $training
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Training $training)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Training  $training
     * @return \Illuminate\Http\Response
     */
    public function destroy(Training $training)
    {
        //
    }
}

resources/views/admin/training/create.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">

			{{ Form::open(['route' => 'admin.partner.store']) }}
				<div class="card-body">
					<div class="row">
						<fieldset>
                            <div class="row">
							{{ Form::bsText('col-sm-6', __('Name'), 'name', old('name'), __('Name'), ['required' => '']) }}

							{{ Form::bsText('col-sm-6', __('Username'), 'username', old('username'), __('Username'), ['required' => '']) }}

							{{ Form::bsText('col-sm-6', __('Email'), 'email', old('email'), __('Email'), ['required' => '']) }}

							{{ Form::bsTextarea('col-sm-6', __('Address'), 'address', old('address'), __('Address'), ['' => '']) }}

							{{ Form::bsPassword('col-sm-6', __('Password'), 'password', __('Password'), ['required' => '']) }}

							{{ Form::bsPassword('col-sm-6', __('Retype Password'), 'password_confirmation', __('Retype Password'), ['required' => '']) }}
                            </div>
						</fieldset>
					</div>
				</div>
				<div class="card-footer bg-whitesmoke text-center">
					{{ Form::submit(__('Save'), ['class' => 'btn btn-primary']) }}
					{{ link_to(route('user.index'),__('Cancel'), ['class' => 'btn btn-danger']) }}
				</div>
			{{ Form::close() }}

		</div>
	</div>
</div>
@endsection

resources/views/admin/training/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">

			{{ Form::open(['route' => ['admin.partner.update', $data->id], 'method' => 'put', 'files' => true]) }}
				<div class="card-body">
					<div class="row">
						{{ Form::bsText('col-sm-6', __('Name'), 'name', $data->name, __('Name'), ['required' => '']) }}

						{{ Form::bsEmail('col-sm-6', __('E-Mail'), 'email', $data->email, __('E-Mail'), ['required' => '']) }}

						{{ Form::bsTextarea('col-sm-12', __('Address'), 'address', $data->address, __('Address'), ['required' => '']) }}
					</div>
				</div>
				<div class="card-footer bg-whitesmoke text-center">
					{{ Form::submit(__('Save'), ['name' => 'submit', 'class' => 'btn btn-primary']) }}
					{{ link_to(url()->previous(), __('Cancel'), ['class' => 'btn btn-danger']) }}
				</div>
			{{ Form::close() }}

		</div>
	</div>
</div>
@endsection

resources/views/admin/training/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">
			<div class="card-header">
                <a href="{{ route('admin.partner.create') }}" class="btn btn-icon btn-success" title="{{ __('Create') }}"><i class="fa fa-plus"></i></a>
				<button class="btn btn-icon btn-secondary" data-toggle="modal" data-target="#filterModal" title="{{ __('Filter') }}"><i class="fa fa-filter"></i></button>
            	<button class="btn btn-icon btn-secondary" onclick="reloadTable()" title="{{ __('Refresh') }}"><i class="fa fa-sync"></i></i></button>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-striped" id="table4data">
						<thead>
							<tr>
								<th>
									<div class="checkbox icheck"><label><input type="checkbox" name="selectData"></label></div>
								</th>
								<th>{{ __('Created At') }}</th>
								<th>{{ __('Name') }}</th>
								<th>{{ __('Slug') }}</th>
								<th>{{ __('Batch') }}</th>
								<th>{{ __('Action') }}</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			<div class="card-footer bg-whitesmoke">
                <button class="btn btn-danger btn-sm" name="deleteData" title="{{ __('Delete') }}">{{ __('Delete') }}</button>
			</div>
		</div>

	</div>
</div>
@endsection

@section('script')
<script>
	var table;
	$(document).ready(function() {
		table = $('#table4data').DataTable({
			processing: true,
			serverSide: true,
			"ajax": {
				"url": "{{ route('admin.training.list') }}",
				"type": "POST",
				"data": function (d) {
				  d._token = "{{ csrf_token() }}";
		        }
			},
			columns: [
				{ data: 'DT_RowIndex', name: 'DT_RowIndex', 'searchable': false },
				{ data: 'created_at', name: 'created_at' },
				{ data: 'name', name: 'name' },
				{ data: 'slug', name: 'slug' },
				{ data: 'batch', name: 'batch' },
				{ data: 'action', name: 'action', "orderable": false, 'searchable': false }
			],
			"order": [[ 1, 'desc' ]],
			"columnDefs": [
			{   
          		"targets": [ 0, -1 ], //last column
          		"orderable": false, //set not orderable
      		},
      		],
      		"drawCallback": function(settings) {
      			$('input[name="selectData"], input[name="selectedData[]"]').iCheck({
      				checkboxClass: 'icheckbox_flat-green',
      				radioClass: 'iradio_flat-green',
      				increaseArea: '20%' /* optional */
      			});
      			$('[name="selectData"]').on('ifChecked', function(event){
      				$('[name="selectedData[]"]').iCheck('check');
      			}).on('ifUnchecked', function(event){
      				$('[name="selectedData[]"]').iCheck('uncheck');
      			});
      		},
  		});

		$('[name="deleteData"]').click(function(event) {
			if ($('[name="selectedData[]"]:checked').length > 0) {
				event.preventDefault();
				var selectedData = $('[name="selectedData[]"]:checked').map(function(){
					return $(this).val();
				}).get();
				swal({
			      	title: '{{ __("Are you sure want to delete this data?") }}',
			      	text: '',
			      	icon: 'warning',
			      	buttons: ['{{ __("Cancel") }}', true],
			      	dangerMode: true,
			    })
			    .then((willDelete) => {
			      	if (willDelete) {
			      		$.ajax({
							url : "{{ route('user.destroy') }}",
							type: "DELETE",
							dataType: "JSON",
							data: {"_token" : "{{ csrf_token() }}", "selectedData" : selectedData},
							success: function(data)
							{
								reloadTable();
							},
							error: function (jqXHR, textStatus, errorThrown)
							{
								if (JSON.parse(jqXHR.responseText).status) {
									swal("{{ __('Failed!') }}", '{{ __("Data cannot be deleted.") }}', "warning");
								} else {
									swal(JSON.parse(jqXHR.responseText).message, "", "error");
								}
							}
						});
			      	}
    			});
			} else {
				swal("{{ __('Please select a data..') }}", "", "warning");
			}
		});

        // Reset Password
		// $('[name="resetPassword"]').click(function(event) {
		// 	if ($('[name="selectedData[]"]:checked').length > 0) {
		// 		event.preventDefault();
		// 		var selectedData = $('[name="selectedData[]"]:checked').map(function(){
		// 			return $(this).val();
		// 		}).get();
		// 		swal({
		// 	      	title: '{{ __("Are you sure want to reset this account?") }}',
		// 	      	text: '',
		// 	      	icon: 'warning',
		// 	      	buttons: ['{{ __("Cancel") }}', true],
		// 	      	dangerMode: true,
		// 	    })
		// 	    .then((willReset) => {
		// 	      	if (willReset) {
		// 	      		$.ajax({
		// 					url : "{{ route('user.reset') }}",
		// 					type: "DELETE",
		// 					dataType: "JSON",
		// 					data: {"_token" : "{{ csrf_token() }}", "selectedData" : selectedData},
		// 					success: function(data)
		// 					{
		// 						swal("{{ __('Success!') }}", '{{ __("Reseting succeed.") }}', "success");
		// 						reloadTable();
		// 					},
		// 					error: function (jqXHR, textStatus, errorThrown)
		// 					{
		// 						if (JSON.parse(jqXHR.responseText).status) {
		// 							swal("{{ __('Failed!') }}", '{{ __("Data cannot be reseted.") }}', "warning");
		// 						} else {
		// 							swal(JSON.parse(jqXHR.responseText).message, "", "error");
		// 						}
		// 					}
		// 				});
		// 	      	}
    	// 		});
		// 	} else {
		// 		swal("{{ __('Please select a data..') }}", "", "warning");
		// 	}
		// });
	});

	function reloadTable() {
	    table.ajax.reload(null,false); //reload datatable ajax
	    $('[name="selectData"]').iCheck('uncheck');
	}

	function filter() {
		reloadTable();
		$('#filterModal').modal('hide');
	}
</script>

<!-- Modal -->
<!-- <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="filterModallLabel">{{ __('Filter') }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{{ Form::open(['url' => '#', 'files' => true]) }}
				<div class="modal-body">
					<div class="container-fluid">
						<div class="row">
						</div>
					</div>
				</div>
				<div class="modal-footer bg-whitesmoke d-flex justify-content-center">
					{{ Form::button(__('Filter'), ['class' => 'btn btn-primary', 'onclick' => 'filter()']) }}
					{{ Form::button(__('Cancel'), ['class' => 'btn btn-secondary', ' data-dismiss' => 'modal']) }}
				</div>
			{{ Form::close() }}
		</div>
	</div>
</div> -->
@endsection

<!--  Form::bsSelect('col-12', __('Type'), 'type', $types, null, __('Select'), ['placeholder' => __('Select')]) }} -->

resources/views/admin/training/show.blade.php
@extends('layouts.main')

@section('content')
<div class="row mt-sm-4">
	<div class="col-12 col-md-12 col-lg-5">
		<div class="card profile-widget">
			<div class="profile-widget-header">                     
				<img alt="image" src="{{ asset(($data->user->avatar) ? : 'img/avatar/avatar.png')  }}" class="rounded-circle profile-widget-picture">
			</div>
			<div class="profile-widget-description">
				<div class="profile-widget-name">{{ $data->name }} <div class="text-muted d-inline font-weight-normal"><div class="slash"></div> {{ $data->email }}</div></div>
			</div>
		</div>
	</div>
	<div class="col-12 col-md-12 col-lg-7">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card">
			<div class="card-header">
				<h4>{{ __('Edit Profile') }}</h4>
			</div>
			{{ Form::open(['route' => ['admin.partner.update', $data->id], 'method' => 'put', 'files' => true]) }}
			<div class="card-body">
				<div class="row">

					{{ Form::bsText('col-sm-6', __('Name'), 'name', $data->name, __('Name'), ['' => '']) }}

					{{ Form::bsEmail('col-sm-6', __('E-Mail'), 'email', $data->email, __('E-Mail'), ['required' => '']) }}

					{{ Form::bsTextarea('col-sm-12', __('Address'), 'address', $data->address, __('address'), ['' => '']) }}
				</div>
			</div>
			<div class="card-footer text-right">
				{{ Form::submit(__('Save'), ['name' => 'submit', 'class' => 'btn btn-primary']) }}
			</div>
			{{ Form::close() }}
		</div>

	</div>
</div>
@endsection