routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login', ['title' => 'Login']);
});

// Route::get('/register/success', function () {
//     $view = [
//         'title' => 'Thanks for Registration!',
//     ];
//     return view('welcome', $view);
// })->name('register.success');

Auth::routes();
Route::post('/login/submit', 'Auth\LoginController@Login')->name('login.submit');

// School
Route::prefix('school')->name('school.')->group(function () {
    Route::get('register', 'SchoolController@create')->name('register');
    Route::post('/', 'SchoolController@store')->name('store');
});

Route::prefix('get')->name('get.')->group( function() {
    Route::post('city', 'GetController@city')->name('city');
    Route::post('chart', 'GetController@adminChartSchool')->name('chart');
    Route::post('chartReqJava', 'GetController@chartReqJava')->name('chartReqJava');
    Route::post('chartReqOutJava', 'GetController@chartReqOutJava')->name('chartReqOutJava');
    Route::post('schoolStatus', 'GetController@schoolStatus')->name('schoolStatus');
    Route::post('studentStatus', 'GetController@studentStatus')->name('studentStatus');
    Route::post('regency', 'GetController@regency')->name('regency');
    Route::post('school', 'GetController@school')->name('school');
    Route::post('generation', 'GetController@generation')->name('generation');
    Route::post('unitScore', 'GetController@unitScore')->name('unitScore');
    Route::post('studentAchievement', 'GetController@studentAchievement')->name('studentAchievement');
    Route::post('schoolAchievement', 'GetController@schoolAchievement')->name('schoolAchievement');
    Route::post('student', 'GetController@student')->name('student');
    Route::post('schoolAcademy', 'GetController@schoolAcademy')->name('schoolAcademy');
    Route::post('schoolClassIntensif', 'GetController@schoolClassIntensif')->name('schoolClassIntensif');
    Route::post('talentPool', 'GetController@talentPool')->name('talentPool');
    Route::post('academy', 'GetController@academy')->name('academy');
});


// default guard
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('user', 'UserController')->except(['destroy']);
    Route::prefix('user')->name('user.')->group(function(){
        Route::post('list', 'UserController@list')->name('list');
        Route::post('reset', 'UserController@reset')->name('reset');
        Route::delete('destroy', 'UserController@destroy')->name('destroy');
    });
    Route::resource('psychotest-result', 'PsychologicalTestResultController')->except(['list', 'show']);
    Route::prefix('psychotest-result')->name('psychotest-result.')->group(function(){
        Route::post('mbti_list', 'PsychologicalTestResultController@mbti_list')->name('mbti_list');
        Route::get('{psychologicalTest}/attempt/{psychologicalTestAttempt}/result', 'PsychologicalTestResultController@mbti_show')->name('mbti_show');

        Route::post('disc_list', 'PsychologicalTestResultController@disc_list')->name('disc_list');
        Route::get('{user}/result', 'PsychologicalTestResultController@disc_show')->name('disc_show');
    });
});

// guard Student
Route::middleware(['auth:student'])->group(function () {
    Route::namespace('Student')->prefix('student')->name('student.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::post('/home/store', 'HomeController@store')->name('home.store');
        
        // StudentLesson
        Route::prefix('studentLesson')->name('studentLesson.')->group(function(){
            Route::post('list', 'StudentLessonController@list')->name('list');
            Route::post('reset', 'StudentLessonController@reset')->name('reset');
            Route::delete('destroy', 'StudentLessonController@destroy')->name('destroy');
            Route::post('preCreate', 'StudentLessonController@preCreate')->name('preCreate');
        });
        Route::resource('studentLesson', 'StudentLessonController')->except(['destroy']);

        // profile
        Route::prefix('profile')->name('profile.')->group(function(){
            Route::get('preview/{student}','ProfileController@preview')->name('preview');
            Route::get('download/{student}','ProfileController@download')->name('download');
            Route::post('list', 'ProfileController@list')->name('list');
            Route::post('reset', 'ProfileController@reset')->name('reset');
            Route::delete('destroy', 'ProfileController@destroy')->name('destroy');
        });
        Route::resource('profile', 'ProfileController')->except(['destroy']);
        
        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Teacher
Route::middleware(['auth:teacher'])->group(function () {
    Route::namespace('Teacher')->prefix('facilitator')->name('teacher.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');

        // school
        Route::prefix('school')->name('school.')->group(function(){
            Route::post('list', 'SchoolController@list')->name('list');
            Route::post('reset', 'SchoolController@reset')->name('reset');
            Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
        });
        Route::resource('school', 'schoolController')->except(['destroy']);

        // lesson
        Route::prefix('lesson')->name('lesson.')->group(function(){
            Route::post('list', 'LessonController@list')->name('list');
            Route::post('reset', 'LessonController@reset')->name('reset');
            Route::delete('destroy', 'LessonController@destroy')->name('destroy');
        });
        Route::resource('lesson', 'LessonController')->except(['destroy']);

        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('upload', 'StudentController@upload')->name('upload');
            Route::post('import', 'StudentController@import')->name('import');
            Route::post('export', 'StudentController@export')->name('export');
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });
        Route::resource('student', 'StudentController')->except(['destroy']);

        // new student
        Route::prefix('newStudent')->name('newStudent.')->group(function(){
            Route::get('/import', 'NewStudentController@import')->name('import');
            Route::post('list', 'NewStudentController@list')->name('list');
            Route::post('reset', 'NewStudentController@reset')->name('reset');
            Route::delete('destroy', 'NewStudentController@destroy')->name('destroy');
            Route::delete('approve', 'NewStudentController@approve')->name('approve');
            Route::delete('reject', 'NewStudentController@reject')->name('reject');
        });
        Route::resource('newStudent', 'NewStudentController')->except(['destroy']);

        // Update
        Route::prefix('update')->name('update.')->group(function () {
            Route::post('list', 'UpdateController@list')->name('list');
            Route::get('/', 'UpdateController@index')->name('index');
            Route::prefix('status')->name('status.')->group(function () {
                Route::get('/', 'UpdateController@status')->name('index');
            });
        });

        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Partner
Route::middleware(['auth:partner'])->group(function () {
    Route::namespace('Partner')->prefix('partner')->name('partner.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        
        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Datakrama\Eloquid\Traits\Uuids;

class Student extends Model
{
	use Uuids;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'school_origin', 'phone_number', 'study_status', 'registered_status', 'generation_id', 'place_of_birth', 'date_of_birth', 'gender', 'identition_number', 'city_id', 'address', 'weight', 'height'
    ];
    
    public function generation() {
    	return $this->belongsTo('App\Generation');
    }

    public function school() {
    	return $this->hasOneThrough('App\School', 'App\Generation', 'id', 'id', 'generation_id', 'school_id');
    }

    public function studentStatuses() {
        return $this->hasMany('App\StudentStatus');
    }

    public function statuses() {
        return $this->belongsToMany('App\Status', 'student_statuses')->using('App\StudentStatus')->withTimestamps()->withPivot('created_at');
    }

    public function status() {
    	return $this->statuses()->newest();
    }

    public function statusLatest() {
        return $this->hasOneThrough('App\Status', 'App\StudentStatus', 'student_id', 'id', 'id', 'status_id')->latest();
    }

    public function level() {
    	return $this->status()->level();
    }

    public function user() {
    	return $this->hasOneThrough('App\User', 'App\StudentAccount', 'student_id', 'id', 'id', 'user_id');
    }

    public function city() {
        return $this->belongsTo('App\City');
    }

    public function documents() {
    	return $this->hasMany('App\StudentDocument');
    }

    public function lessonAchievements() {
        return $this->hasMany('App\StudentLessonAchievement');
    }

    // public function achievements() {
    //     return $this->hasManyThrough('App\LessonAchievement', 'App\StudentLessonAchievement', 'student_id', 'id', 'id', 'lesson_achievement_id');
    // }

    public function lesson() {
        return $this->hasMany('App\StudentLesson');
    }
    
    public function alocatedStudent() {
        return $this->hasMany('App\AlocatedStudent');
    }

    // end of relation function

    // attribute function
    public function getProfilePercentageAttribute() {
        $column = collect($this->getAttributes())->except(['id', 'created_at', 'updated_at', 'pivot']);
        return substr(($column->filter(function ($item) { return $item; })->count() / $column->count())*100, 0 , 4 );
    }

}

app/Http/Controllers/Student/AccountController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use Spatie\Image\Manipulations;
use Illuminate\Http\Request;
use Spatie\Image\Image;
use App\User;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, User $user)
    {
        $view = [
            'title' => __('Account Detail'),
            'breadcrumbs' => [
                route('student.account.index') => __('Account'),
                null => __('Detail')
            ],
            'data' => $user
        ];
        if ($request->is('student/account/me/*')) {
            $addonView = [
                'subtitle' => __('Hi') . ', ' . $user->name . '!',
                'description' => __('Change information about yourself on this page.'),
            ];
            $view = array_merge($view, $addonView);
        }
        return view('student.account.show', $view);
    }

    /**
     * Display the current user's resource.
     * 
     * @return @show()
     */
    public function me(Request $request)
    {
        return $this->show($request, auth()->guard('admin')->user());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        if ($request->filled('password')) {
            $request->merge(['password' => Hash::make($request->password)]);
        } else {
            $request->merge(['password' => $user->password]);
        }
        if ($request->hasFile('photo')) {
            $request->merge(['avatar' => $this->uploadPhoto($request)]);
        }
        $user->fill($request->all());
        $user->save();
        return redirect(url()->previous())->with('alert-success', __($this->updatedMessage));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Upload photo
     * 
     * @param  \App\Teacher  $user
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $oldFile
     * @return string
     */
    public function uploadPhoto(Request $request)
    {
        Image::load($request->photo)
            ->fit(Manipulations::FIT_CROP, 150, 150)
            ->optimize()
            ->save();
        $filename = 'photo_'.date('d_m_Y_H_i_s_').md5(uniqid(rand(), true)).'.'.$request->photo->extension();
        $path = $request->photo->storeAs('public/student/photo/', $filename);
        return $filename;
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        //
    }
}

resources/views/student/passport/class.blade.php
@extends('layouts.main')

@section('style')
<style>
  .card .form-group:hover .table-links {
    opacity: 1;
  }
</style>
@endsection
@section('content')
<div class="row">
    <div class="col-lg-8">
        @if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif
        <div class="">
            <!-- <div class="card-header"><h4>Kelas Aktif</h4></div> -->
            @foreach($classes as $class)
                <form action="{{ route('student.studentLesson.preCreate') }}" method="post">
                {{ csrf_field() }}
                    <article class="article article-style-c">
                        <div class="article-details">
                            <div class="article-title"><a href=""><h5>{{ $class->name }}</h5></a></div>
                            <div class="article-category"><a href="#">{{ $class->teacher ? $class->teacher->name : '' }}</a> <div class="bullet"></div> <a href="#">{{ $class->teacher ? $class->teacher->position : '' }}</a></div>
                            <p>{{ $class->description }}</p>
                            <input type="hidden" name="class" value="{{ $class->id }}">
                            <input type="submit" name="submit" value="Pilih kelas" class="btn btn-primary pilihClass">
                                <!-- <a href="" class="pilihClass">Pilih Kelas <i class="fas fa-chevron-right"></i></a> -->
                        </div>
                    </article>
                </form>
            @endforeach
        </div>
    </div>
    
    <div class="col-lg-4">
        <div class="card">
            <!-- PENCAPAIAN RATA RATA -->
            <div class="card-header"><h4>Pencapaian Rata-rata</h4></div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6 mb-4">

                        <div class="wrap mt-2">
                            <div class="float-right font-weight-bold text-muted">5 <small>/ </small> 10 Kali</div>
                            <div class="font-weight-bold mb-1">Band Uang</div>
                            <div class="p   rogress" data-height="15" style="height: 15px;">
                                <div class="progress-bar" role="progressbar" data-width="56%" aria-valuenow="56" aria-valuemin="0" aria-valuemax="100" style="width: 56%;">50%</div>
                            </div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">125 Stack <small>/ </small> 90 Menit</div>
                            <div class="font-weight-bold">Rata - rata</div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">300 Stack <small>/ </small> 90 Menit</div>
                            <div class="font-weight-bold">KKM</div>
                        </div>

                    </div>
                    <div class="col-lg-6 mb-4">

                        <div class="wrap mt-2">
                            <div class="float-right font-weight-bold text-muted">3 <small>/ </small>10 Kali</div>
                            <div class="font-weight-bold mb-1">Isi Kaset</div>
                            <div class="progress" data-height="15" style="height: 15px;">
                                <div class="progress-bar" role="progressbar" data-width="30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">30%</div>
                            </div>
                        </div>

                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">02:49 Menit</div>
                            <div class="font-weight-bold">Rata - rata</div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">02:00 Menit</div>
                            <div class="font-weight-bold">KKM</div>
                        </div>

                    </div>
                    <div class="col-lg-6 mb-4">
                        <div class="wrap mt-2">
                            <div class="float-right font-weight-bold text-muted">4 <small>/ </small> 10 Kali</div>
                            <div class="font-weight-bold mb-1">Bongkar Kaset</div>
                            <div class="progress" data-height="15" style="height: 15px;">
                                <div class="progress-bar" role="progressbar" data-width="40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;">40%</div>
                            </div>
                        </div>

                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">02:42 Menit</div>
                            <div class="font-weight-bold">Rata - rata</div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">03:00 Menit</div>
                            <div class="font-weight-bold">KKM</div>
                        </div>
                    </div>
                    <div class="col-lg-6 mb-4">
                        <div class="wrap mt-2">
                            <div class="float-right font-weight-bold text-muted">4 <small>/ </small> 10 Kali</div>
                            <div class="font-weight-bold mb-1">Pengepakan Plastik</div>
                            <div class="progress" data-height="15" style="height: 15px;">
                                <div class="progress-bar" role="progressbar" data-width="40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;">40%</div>
                            </div>
                        </div>

                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">01:52 Menit</div>
                            <div class="font-weight-bold">Rata - rata</div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">02:00 Menit</div>
                            <div class="font-weight-bold">KKM</div>
                        </div>
                    </div>
                    <div class="col-lg-6 mb-4">
                        <div class="wrap mt-2">
                            <div class="float-right font-weight-bold text-muted">4 <small>/ </small> 20 Kali</div>
                            <div class="font-weight-bold mb-1">Pengepakan Kanvas</div>
                            <div class="progress" data-height="15" style="height: 15px;">
                            <div class="progress-bar" role="progressbar" data-width="20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">20%</div>
                            </div>
                        </div>

                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">02:15 Menit</div>
                            <div class="font-weight-bold">Rata - rata</div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">02:30 Menit</div>
                            <div class="font-weight-bold">KKM</div>
                        </div>
                    </div>
                    <div class="col-lg-6 mb-4">
                        <div class="wrap mt-2">
                            <div class="float-right font-weight-bold text-muted">4 <small>/ </small> 10 Kali</div>
                            <div class="font-weight-bold mb-1">Mengisi Kembali</div>
                            <div class="progress" data-height="15" style="height: 15px;">
                            <div class="progress-bar" role="progressbar" data-width="40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;">40%</div>
                            </div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">00:52 Menit</div>
                            <div class="font-weight-bold">Rata - rata</div>
                        </div>
                        <div class="wrap mt-3">                            
                            <div class="float-right font-weight-bold text-muted">01:00 Menit</div>
                            <div class="font-weight-bold">KKM</div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- PENUTUP PENCAPAIAN RATA RATA -->
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
$(document).ready(function() {
     $(".add-more").click(function(){ // If button with class "add-more" clicked
        let score = $("[name='score[]']").val(); // Get score input
        if(score.length < 1) {
            swal({
                title: "Mohon isi Form terlebih dahulu!",
                icon: "error",
                button: "Kembali",
            });
            return false
        }
        let clonned = $("#input-form").clone().prependTo("#form-input"); // Clonning form
        clonned.find("[name='skill[]']").val($(this).parents('.form-group').find("[name='skill[]']").val()); // Auto selected skill if clonning form
        clonned.closest('.form-group').find("[name='skill[]']").prop('disabled', true); // Disabled skill field
        clonned.closest('.form-group').find("[name='score[]']").prop('disabled', true); // Disabled score field
        clonned.closest('.form-group').find(".upload-photo").addClass('d-none'); // // Hide upload photo on add form
        clonned.closest('.form-group').find(".table-links").removeClass('d-none'); // Hide table links on hover
        $(this).parents('.form-group').find("[name='score[]']").val(''); // Empty the input skill
        $("#form-input .check-more").removeClass("d-none"); // Display checklist button
        $("#form-input .add-more").remove(); // Remove add button
    });

    $(".remove-more").click(function(){ // If button with class "remove-more" clicked
        $(this).parents("#input-form").remove(); // Deleted the cloned form
    });

    $(".custom-select").change(function(){ // If one option is selected
        if($(this).val() == "band_uang"){ // Detect if band_uang selected
            $(this).parents('.form-group').find(".input-group-text").text("Stack (30 Mnt)"); // Show Stack (30 Mnt) if band_uang selected
        } else {
            $(this).parents('.form-group').find(".input-group-text").text("Minutes"); // Show Minutes else band_uang selected
        }
    });
    
    $(document.body).on('click', '.action-upload' ,function(){
        $(this).closest('.form-group').find(".upload-photo").removeClass('d-none');
        $(this).addClass('action-hide').removeClass('.action-upload');
        $(this).text("Hide Upload");
    });

    $(document.body).on('click', '.action-hide' ,function(){
        $(this).closest('.form-group').find(".upload-photo").addClass('d-none');
        $(this).addClass('action-upload').removeClass('action-hide');
        $(this).text("Show Upload");
    });
});

$.uploadPreview({
  input_field: "#image-upload",   // Default: .image-upload
  preview_box: "#image-preview",  // Default: .image-preview
  label_field: "#image-label",    // Default: .image-label
  label_default: "Choose File",   // Default: Choose File
  label_selected: "Change File",  // Default: Change File
  no_label: false,                // Default: false
  success_callback: null          // Default: null
});
</script>
@endsection