routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login', ['title' => 'Login']);
});

// Route::get('/register/success', function () {
//     $view = [
//         'title' => 'Thanks for Registration!',
//     ];
//     return view('welcome', $view);
// })->name('register.success');

Auth::routes();
Route::post('/login/submit', 'Auth\LoginController@Login')->name('login.submit');

// School
Route::prefix('school')->name('school.')->group(function () {
    Route::get('register', 'SchoolController@create')->name('register');
    Route::post('/', 'SchoolController@store')->name('store');
});

Route::prefix('get')->name('get.')->group( function() {
    Route::post('city', 'GetController@city')->name('city');
    Route::post('chart', 'GetController@adminChartSchool')->name('chart');
    Route::post('chartReqJava', 'GetController@chartReqJava')->name('chartReqJava');
    Route::post('chartReqOutJava', 'GetController@chartReqOutJava')->name('chartReqOutJava');
    Route::post('schoolStatus', 'GetController@schoolStatus')->name('schoolStatus');
    Route::post('studentStatus', 'GetController@studentStatus')->name('studentStatus');
    Route::post('regency', 'GetController@regency')->name('regency');
    Route::post('school', 'GetController@school')->name('school');
    Route::post('generation', 'GetController@generation')->name('generation');
    Route::post('unitScore', 'GetController@unitScore')->name('unitScore');
    Route::post('studentAchievement', 'GetController@studentAchievement')->name('studentAchievement');
    Route::post('schoolAchievement', 'GetController@schoolAchievement')->name('schoolAchievement');
    Route::post('student', 'GetController@student')->name('student');
    Route::post('schoolAcademy', 'GetController@schoolAcademy')->name('schoolAcademy');
    Route::post('schoolClassIntensif', 'GetController@schoolClassIntensif')->name('schoolClassIntensif');
    Route::post('talentPool', 'GetController@talentPool')->name('talentPool');
    Route::post('academy', 'GetController@academy')->name('academy');
});


// default guard
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('user', 'UserController')->except(['destroy']);
    Route::prefix('user')->name('user.')->group(function(){
        Route::post('list', 'UserController@list')->name('list');
        Route::post('reset', 'UserController@reset')->name('reset');
        Route::delete('destroy', 'UserController@destroy')->name('destroy');
    });
    Route::resource('psychotest-result', 'PsychologicalTestResultController')->except(['list', 'show']);
    Route::prefix('psychotest-result')->name('psychotest-result.')->group(function(){
        Route::post('mbti_list', 'PsychologicalTestResultController@mbti_list')->name('mbti_list');
        Route::get('{psychologicalTest}/attempt/{psychologicalTestAttempt}/result', 'PsychologicalTestResultController@mbti_show')->name('mbti_show');

        Route::post('disc_list', 'PsychologicalTestResultController@disc_list')->name('disc_list');
        Route::get('{user}/result', 'PsychologicalTestResultController@disc_show')->name('disc_show');
    });
});

// guard Student
Route::middleware(['auth:student'])->group(function () {
    Route::namespace('Student')->prefix('student')->name('student.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::post('/home/store', 'HomeController@store')->name('home.store');
        
        // StudentLesson
        Route::prefix('studentLesson')->name('studentLesson.')->group(function(){
            Route::post('list', 'StudentLessonController@list')->name('list');
            Route::post('reset', 'StudentLessonController@reset')->name('reset');
            Route::delete('destroy', 'StudentLessonController@destroy')->name('destroy');
            Route::post('preCreate', 'StudentLessonController@preCreate')->name('preCreate');
        });
        Route::resource('studentLesson', 'StudentLessonController')->except(['destroy']);

        // profile
        Route::prefix('profile')->name('profile.')->group(function(){
            Route::get('preview/{student}','ProfileController@preview')->name('preview');
            Route::get('download/{student}','ProfileController@download')->name('download');
            Route::post('list', 'ProfileController@list')->name('list');
            Route::post('reset', 'ProfileController@reset')->name('reset');
            Route::delete('destroy', 'ProfileController@destroy')->name('destroy');
        });
        Route::resource('profile', 'ProfileController')->except(['destroy']);
        
        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Teacher
Route::middleware(['auth:teacher'])->group(function () {
    Route::namespace('Teacher')->prefix('facilitator')->name('teacher.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');

        // school
        Route::prefix('school')->name('school.')->group(function(){
            Route::post('list', 'SchoolController@list')->name('list');
            Route::post('reset', 'SchoolController@reset')->name('reset');
            Route::delete('destroy', 'SchoolController@destroy')->name('destroy');
        });
        Route::resource('school', 'schoolController')->except(['destroy']);

        // lesson
        Route::prefix('lesson')->name('lesson.')->group(function(){
            Route::post('list', 'LessonController@list')->name('list');
            Route::post('reset', 'LessonController@reset')->name('reset');
            Route::delete('destroy', 'LessonController@destroy')->name('destroy');
        });
        Route::resource('lesson', 'LessonController')->except(['destroy']);

        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('upload', 'StudentController@upload')->name('upload');
            Route::post('import', 'StudentController@import')->name('import');
            Route::post('export', 'StudentController@export')->name('export');
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });
        Route::resource('student', 'StudentController')->except(['destroy']);

        // new student
        Route::prefix('newStudent')->name('newStudent.')->group(function(){
            Route::get('/import', 'NewStudentController@import')->name('import');
            Route::post('list', 'NewStudentController@list')->name('list');
            Route::post('reset', 'NewStudentController@reset')->name('reset');
            Route::delete('destroy', 'NewStudentController@destroy')->name('destroy');
            Route::delete('approve', 'NewStudentController@approve')->name('approve');
            Route::delete('reject', 'NewStudentController@reject')->name('reject');
        });
        Route::resource('newStudent', 'NewStudentController')->except(['destroy']);

        // Update
        Route::prefix('update')->name('update.')->group(function () {
            Route::post('list', 'UpdateController@list')->name('list');
            Route::get('/', 'UpdateController@index')->name('index');
            Route::prefix('status')->name('status.')->group(function () {
                Route::get('/', 'UpdateController@status')->name('index');
            });
        });

        // Account
        Route::prefix('account')->name('account.')->group(function(){
            Route::get('me', 'AccountController@me')->name('me');
            Route::post('list', 'AccountController@list')->name('list');
            Route::post('reset', 'AccountController@reset')->name('reset');
            Route::delete('destroy', 'AccountController@destroy')->name('destroy');
            Route::put('update/{user}', 'AccountController@update')->name('update');
        });
        Route::resource('account', 'AccountController')->except(['update', 'destroy']);
    });

});

// guard Partner
Route::middleware(['auth:partner'])->group(function () {
    Route::namespace('Partner')->prefix('partner')->name('partner.')->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        
        // student
        Route::prefix('student')->name('student.')->group(function(){
            Route::get('preview/{student}','StudentController@preview')->name('preview');
            Route::get('download/{student}','StudentController@download')->name('download');
            Route::post('list', 'StudentController@list')->name('list');
            Route::post('reset', 'StudentController@reset')->name('reset');
            Route::delete('destroy', 'StudentController@destroy')->name('destroy');
        });

app/Http/Controllers/Admin/SchoolController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\SchoolRequest;
use DataTables;
use App\Department;
use App\Province;
use App\School;
use App\Status;
use App\Level;
use App\City;
use Form;

class SchoolController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $view = [
            'title' => __('Schools'),
            'status' => Status::first(),
            'levels' => Level::whereHas('statuses', function ($query) {
                            $query->where('intention', 'school');
                        })->orderBy('order', 'asc')->pluck('name', 'id')->toArray(),
            'provinces' => Province::orderBy('name', 'asc')->pluck('name', 'id')->toArray(),
            'columns' => ['Name', 'Status', 'Headmaster Name', 'Headmaster E-Mail', 'PIC Name', 'PIC E-Mail', 'Address'],
        ];
        return view('admin.school.index', $view);
    }

    /**
     * Show a listing of the resource for datatable.
     * 
     * @param  \Illuminate\Http\Request  $request
     */
    public function list(Request $request)
    {
        if ($request->ajax()) {
            $statuses = Status::where('intention', 'school')->get()->map->only('name', 'id')->pluck('name', 'id')->toArray();
            $schools = School::when( ! empty($request->levels), function ($query) use ($request) {
                            $query->whereHas('statuses', function ($subQuery) use ($request) {
                                $subQuery->whereIn('level_id', $request->levels)
                                ->when(! empty($request->statuses), function ($subInQuery) use ($request){
                                    $subInQuery->where('statuses.id', $request->statuses);
                                });
                            });
                        })->when( ! empty($request->provinces), function ($query) use ($request) {
                            $query->whereHas('city', function ($subQuery) use ($request) {
                                $subQuery->whereIn('province_id', $request->provinces)
                                ->when(! empty($request->regencies), function ($subInQuery) use ($request){
                                    $subInQuery->where('id', $request->regencies);
                                });
                            });
                        })->get();

            return DataTables::of($schools)
                ->addColumn('DT_RowIndex', function ($data) {
                    return '<div class="checkbox icheck"><label><input type="checkbox" name="selectedData[]" value="'.$data->id.'"></label></div>';
                })
                ->editColumn('created_at', function ($data) {
                    return (date('d-m-Y H:i:s', strtotime($data->created_at)));
                })
                ->addColumn('status', function ($data) use ($statuses) {
                    // static permission
                    if (! auth()->user()->should('student_statuses')) {
                        return $data->statuses()->count()
                                ? $data->statuses()->latest()->first()->name
                                : 'Registerred';
                    }
                    return Form::bsSelect('rounded-fill', null, 'status', $statuses, (
                        $data->statuses()->latest()->first() 
                            ? $data->statuses()->latest()->first()->id 
                            : null
                    ), null, ['data-id' => $data->id]);
                })
                ->addColumn('pic_name', function ($data) {
                    return $data->pics->first()
                                ? $data->pics()->first()->name
                                : '-';
                })
                ->addColumn('pic_email', function ($data) {
                    return $data->pics->first()
                                ? $data->pics()->first()->email
                                : '-';
                })
                // ->addColumn('action', function ($data) {
                //     return '<a class="btn btn-icon btn-sm btn-info" href="'.route('admin.teacher.show', $data->id).'" title="'.__("See detail").'"><i class="fa fa-eye"></i></a> <a class="btn btn-icon btn-sm btn-warning" href="'.route('admin.teacher.edit', $data->id).'" title="'.__("Edit").'"><i class="fa fa-edit"></i></a>';
                // })
                ->rawColumns(['DT_RowIndex', 'status', 'pic_name', 'pic_email'])
                ->make(true);
        }
    } 

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = [
            'title' => 'Create school',
            'school_type' => ['negeri','Swasta'],
            'provinces' => Province::pluck('name', 'id')->toArray(),
            'cities' => City::pluck('name', 'id')->toArray(),
            'departments' => array_merge(Department::orderBy('name', 'asc')->pluck('name')->toArray(), [__('Other')]),
            'isoCertificates' => ['Sudah' => 'Sudah', 'Dalam Proses (persiapan dokumen / pembentukan team audit internal / pendampingan)' => 'Dalam Proses (persiapan dokumen / pembentukan team audit internal / pendampingan)', 'Belum' => 'Belum']
        ];

        return view('admin.school.create', $view);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SchoolRequest $request)
    {
        // dd($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(School $school)
    {
        $view = [
            'title' => __('Schools'),
            'data' => $school,
            'pics' => $school->schoolPic,
        ];
        return view('admin.school.show', $view);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, School $school)
    {
        if ($request->filled('status_id')) {
            $school->schoolStatuses()->create(['status_id' => $request->status_id]);
        }
        if ($request->ajax()) {
            return response()->json(['status' => true, 'message' => __($this->savedSettingMessage)]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/school/create.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">

			{{ Form::open(['route' => 'admin.school.store']) }}
				<div class="card-body">
					<div class="row">
						<div class="col-sm-6">
							<fieldset id="school">
								<legend>{{ __('School Data') }}</legend>
								<div class="form-group">
									<label for="input-group">{{ __('Name') }}</LAbel>
									<div class="input-group">
										<select class="custom-select col-sm-3 col-lg-2" id="school" name="school">
											<option value="SMK">SMK</option>
											<option value="SMA">SMA</option>
											<option value="MA">MA</option>
										</select>
										<select class="custom-select col-sm-4 col-lg-3" id="school-type" name="type">
											<option value="Swasta">Swasta</option>
											<option value="Negeri">Negeri</option>
										</select>
										<input type="text" class="form-control" name="name" placeholder="{{ __('School') . ' ' . __('Name') }}...">
									</div>
								</div>
						
								<div class="row">
									{{ Form::bsSelect('col-sm-6', __('Province'), 'province', $provinces, old('province'), __('Province'), ['required' => '']) }}

									{{ Form::bsSelect('col-sm-6', __('City'), 'city_id', $cities, old('city_id'), __('City'), ['required' => '']) }}
								</div>

								{{ Form::bsText(null, __('Since'), 'since', old('since'), __('Ex:') . ' 1999', ['maxlength' => '4', 'required' => '']) }}

								{{ Form::bsPhoneNumber(null, __('School Phone Number'), 'school_phone_number', old('school_phone_number'), __('School Phone Number'), ['maxlength' => '13', 'required' => '']) }}

								{{ Form::bsEmail(null, __('School E-Mail'), 'school_email', old('school_email'), __('Ex:') . ' school@school.sch.id', ['required' => '']) }}

								{{ Form::bsText(null, __('School Website (URL)'), 'school_web', old('school_web'), __('Ex:') . ' Http://school.com', ['required' => '']) }}

								{{ Form::bsTextarea(null, __('Address'), 'address', old('address'), __('Ex:') . ' Dsun.Sukahurip. 02/07', ['required' => '']) }}


								{{ Form::bsText(null, __('Total Student'), 'total_student', old('total_student'), __('Ex:') . ' 999', ['required' => '']) }}

								{{ Form::bsCheckboxList(null, __('Department'), 'department[]', $departments) }}

								{{ Form::bsSelect(null, __('ISO Certificate'), 'iso_certificate', $isoCertificates, old('iso_certificate'), __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}	


							</fieldset>
						</div>
						<div class="col-sm-6">
							<fieldset id="headmaster">
								<legend>{{ __('Headmaster Data') }}</legend>
								{{ Form::bsInlineRadio(null, 'Apakah Kepala Sekolah telah mempelajari proposal BCAP?', 'proposal', ['Sudah' => 'Sudah', 'Belum' => 'Belum'], old('proposal'), ['required' => '']) }}

								{{ Form::bsText(null, __('Name'), 'headmaster_name', old('headmaster_name'), __('Ex: Drs. Eneng, M.A. M.Pd.'), ['required' => '']) }}

								{{ Form::bsEmail(null, __('Headmaster E-Mail'), 'headmaster_email', old('headmaster_email'), __('EX: headmaster@smk1.sch.id'), ['required' => '']) }}

								{{ Form::bsPhoneNumber(null, __('Phone Number'), 'headmaster_phone_number', old('headmaster_phone_number'), __('Phone Number'), ['maxlength' => '13', 'required' => '']) }}
							</fieldset>

							<fieldset id="pic">
								<legend>{{ __('PIC Data') }}</legend>

								{{ Form::bsText(null, __('NIP'), 'pic_nip', old('pic_nip'), __('Ex:') . ' 19860926', ['maxlength' => '20', 'required' => '']) }}

								{{ Form::bsSelect(null, __('Gender'), 'pic_gender', ['Pria' => 'Male', 'Wanita' => 'Female'], old('pic_gender'), __('Choose Gender..'), ['required' => '']) }}
								
								{{ Form::bsText(null, __('Name'), 'pic_name', old('pic_name'), __('Ex: Mauza, S.Pd'), ['required' => '']) }}

								{{ Form::bsEmail(null, __('E-Mail'), 'pic_email', old('pic_email'), __('EX: teacher@smk1.sch.id'), ['required' => '']) }}

								{{ Form::bsPhoneNumber(null, __('Phone Number'), 'pic_phone_number', old('pic_phone_number'), __('Phone Number'), ['maxlength' => '13', 'required' => '']) }}

								{{ Form::bsText(null, __('Date Of Birth'), 'pic_date_of_birth', old('pic_date_of_birth'), __('Choose Date'), ['required' => '']) }}

								{{ Form::bsText(null, __('Position'), 'pic_position', old('pic_position'), __('Ex:') . ' IPA Teacher', ['required' => '']) }}

								{{ Form::bsTextarea(null, __('Address'), 'pic_address', old('pic_address'), __('Ex:') . ' Dsun.Sukahurip. 02/07', ['required' => '']) }}

								{{ Form::bsFile(null, __('Photo'), 'pic_photo', old('pic_photo'), [], [__('Photo with JPG/PNG format up to 5MB.')]) }}
							</fieldset>
						</div>
					</div>
				</div>
				<div class="card-footer bg-whitesmoke text-center">
					{{ Form::submit(__('Save'), ['class' => 'btn btn-primary']) }}
					{{ link_to(route('user.index'),__('Cancel'), ['class' => 'btn btn-danger']) }}
				</div>
			{{ Form::close() }}

		</div>
	</div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function () {
		$('select[name="province"]').change(function() {
			$('select[name="city_id"]').html('<option value="">Select</option>');
			if ($(this).val() != '') {
				$.ajax({
					url : "{{ route('get.city') }}",
					type: "POST",
					dataType: "JSON",
					cache: false,
					data: {'_token' : '{{ csrf_token() }}', 'province' : $(this).val()},
					success: function(data)
					{
					$('select[name="city_id"]')
						$.each(data.result, function(key, value) {
							$('select[name="city_id"]').append('<option value="'+value+'">'+value+'</option>');
						});
					},
					error: function (jqXHR, textStatus, errorThrown)
					{
						$('select[name="city_id"]').html('<option value="">Select</option>');
					}
				});
			}
		});

		$('[name="date_of_birth"]').daterangepicker({
		locale: {format: 'DD-MM-YYYY'},
		singleDatePicker: true,
		});

		// daterangeficker
		$('[name="pic_date_of_birth"]').daterangepicker({
			locale: {format: 'DD-MM-YYYY'},
			singleDatePicker: true,
		});
	});
</script>
@endsection

resources/views/admin/school/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
	<div class="col-12">

		@if (session('alert-success'))
			<div class="alert alert-success alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-success') }}
				</div>
			</div>
		@endif

		@if (session('alert-danger'))
			<div class="alert alert-danger alert-dismissible show fade">
				<div class="alert-body">
					<button class="close" data-dismiss="alert">
						<span>&times;</span>
					</button>
					{{ session('alert-danger') }}
				</div>
			</div>
		@endif

		<div class="card card-primary">

			{{ Form::open(['route' => ['admin.teacher.update', $data->id], 'files' => true, 'method' => 'put']) }}
				<div class="card-body">
					<div class="row">
						<div class="col-sm-6">
							<fieldset>
								<legend></legend>
								{{ Form::bsSelect(null, __('School'), 'school_id', $schools, $data->school_id, __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}

								{{ Form::bsText(null, __('NIP'), 'nip', $data->nip, __('NIP')) }}

								{{ Form::bsText(null, __('Full Name'), 'name', $data->name, __('Full Name'), ['required' => '']) }}

								{{ Form::bsText(null, __('Date of Birth'), 'date_of_birth', '01-01-1990', __('Date Of Birth'), ['required' => '']) }}

								{{ Form::bsSelect(null, __('Gender'), 'gender', ['Laki-Laki' => 'Laki-Laki', 'Perempuan' => 'Perempuan'], $data->gender, __('Select'), ['placeholder' => __('Select'), 'required' => '']) }}

							</fieldset>
						</div>
						<div class="col-sm-6">
							<fieldset>
								<legend></legend>
								{{ Form::bsEmail(null, __('E-Mail'), 'email', $data->email, __('E-Mail'), ['required' => ''], [__('Required to use Gmail')]) }}

								{{ Form::bsPhoneNumber(null, __('Phone Number'), 'phone_number', $data->phone_number, __('Phone Number'), ['maxlength' => '13', 'required' => '']) }}

								{{ Form::bsTextarea(null, __('Address'), 'address', $data->address, __('Address')) }}

								{{ Form::bsText(null, __('Position'), 'position', $data->position, __('Position'), ['required' => '']) }}
							</fieldset>
						</div>
					</div>
					{{ Form::bsCheckbox(null, null, 'terms', 'Agree', __('Data filled above is true and can be accounted for.'), old('terms'), ['required' => '']) }}
				</div>
				<div class="card-footer bg-whitesmoke text-center">
					{{ Form::submit(__('Save'), ['name' => 'submit', 'class' => 'btn btn-primary']) }}
					{{ link_to(url()->previous(), __('Cancel'), ['class' => 'btn btn-danger']) }}
				</div>
			{{ Form::close() }}

		</div>
	</div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function () {
		var cleavePN = new Cleave('[name="phone_number"]', {
			phone: true,
			phoneRegionCode: 'id'
		});
	});
</script>
@endsection